### PR TITLE
Auto alive 

### PR DESCRIPTION
**Pull request by khainee**

### CODE REVIEW

**Comment by 5hojib** [comment]
> 

It's worked on render?

**Comment by khainee** [comment]
It works on all

**Comment by 5hojib** [comment]
> It works on all

Kindly same pull in alpha branch, i will merge now

**Comment by khainee** [comment]
> > It works on all
> 
> Kindly same pull in alpha branch, i will merge no

> > It works on all
> 
> Kindly same pull in alpha branch, i will merge now

when i am running on

**Comment by khainee** [comment]
> > > It works on all
> > 
> > 
> > Kindly same pull in alpha branch, i will merge no
> 
> > > It works on all
> > 
> > 
> > Kindly same pull in alpha branch, i will merge now
> 
> when i am running on port 80 it works i dont know about render ports

I runned web server with ```python3 -m http.server 80```

**Comment by 5hojib** [comment]
> > > It works on all
> > 
> > 
> > Kindly same pull in alpha branch, i will merge no
> 
> > > It works on all
> > 
> > 
> > Kindly same pull in alpha branch, i will merge now
> 
> when i am running on port 80 it works i dont know about render ports

Renders port is dynamic port, randomly selected

**Comment by khainee** [comment]
> > > > It works on all
> > > 
> > > 
> > > Kindly same pull in alpha branch, i will merge no
> > 
> > 
> > > > It works on all
> > > 
> > > 
> > > Kindly same pull in alpha branch, i will merge now
> > 
> > 
> > when i am running on port 80 it works i dont know about render ports
> 
> Renders port is dynamic port, randomly selected

IMG_20230513_215500

Runable on specfic port with ```gunicorn app:app --bind 127.0.0.1:80```

**Comment by 5hojib** [comment]
> > > > > It works on all
> > > > 
> > > > 
> > > > Kindly same pull in alpha branch, i will merge no
> > > 
> > > 
> > > > > It works on all
> > > > 
> > > > 
> > > > Kindly same pull in alpha branch, i will merge now
> > > 
> > > 
> > > when i am running on port 80 it works i dont know about render ports
> > 
> > 
> > Renders port is dynamic port, randomly selected
> 
> IMG_20230513_215500
> 
> Runable on specfic port with `gunicorn app:app --bind 127.0.0.1:80`

Pull request in alpha branch, I'm gonna merge

**Pull request closed without merging**
